version: 2.1
orbs:
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
jobs:
  lint-server:
    docker:
      - image: circleci/node
    working_directory: ~/app/server
    steps:
      - checkout:
          path: ~/app
      - run: npm install
      - run: npm run lint
  lint-client:
    docker:
      - image: circleci/node
    working_directory: ~/app/client
    steps:
      - checkout:
          path: ~/app
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
  build-client:
    docker:
      - image: circleci/node
    working_directory: ~/app/client
    steps:
      - checkout:
          path: ~/app
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
  deploy-staging-server:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: 'gcr.io/${PROJECT_ID}/tpc-server'
      - cloudrun/deploy:
          image: 'gcr.io/${PROJECT_ID}/tpc-server'
          region: us-east1
          args: '--vpc-connector=tcp-server-connector --vpc-egress=all --platform=managed --min-instances 1'
  # deploy-staging-client:
workflows:
  server:
    jobs:
      - lint-server
      - deploy-staging-server
          context:
            - tpc-staging
          filters:
            branches:
              only:
                - staging
  client:
    jobs:
      - lint-client
      - build-client
  
