version: 2.1
jobs:
  lint-server:
    docker:
      - image: circleci/node
    working_directory: ~/app/server
    steps:
      - checkout:
        - path: ~/app
      - run: pwd
      - run: npm install
      - run: npm run lint
workflows:
  lint-server:
    jobs:
      - lint-server
  
