version: 2.1
jobs:
  lint-server:
    docker:
      - image: circleci/node
    working_directory: ~/project/server
    steps:
      - checkout
      - run: pwd
      - run: npm --prefix ~/project/server install
      - run: npm --prefix ~/project/server run lint
workflows:
  lint-server:
    jobs:
      - lint-server
  
