version: 2.1
jobs:
  lint-server:
    docker:
      - image: circleci/node
    working_directory: ~/project/server
    steps:
      - checkout
      - run: cd ~/project/server && npm install
      - run: cd ~/project/server && npm run lint
workflows:
  lint-server:
    jobs:
      - lint-server
  
